import 'bootstrap/dist/css/bootstrap.min.css';
import { clsx } from 'clsx';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';

import { InitToaster } from '@/components/Toaster';

import '@/styles/custom-classes.css';
import '@/styles/variables.css';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	icons: {
		icon: '/favicon.ico'
	}
};

type Props = {
	children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
	return (
		<html lang='en'>
			<body
				className={clsx(geistSans.variable, geistMono.variable, 'bg-light')}
			>
				<NextTopLoader
					color='#4c9148ff'
					initialPosition={0.08}
					crawlSpeed={200}
					height={4}
					crawl={true}
					showSpinner={false}
					easing='ease'
					speed={200}
				/>
				{children}
				<InitToaster />
			</body>
		</html>
	);
}
